### ISSUE TITLE
Add logging/feedback for data transfers from S3 to new Jenkins Master 

### ISSUE THREAD

**Issue by murphyj21** [plus3it/cfn-jenkins#17]
### Problem Description:

Currently during the app install phase of the Jenkins Master build there is no feedback for the data transfer between S3 (sync/JENKINS_HOME) to the new instance. For the uninitiated it appears that the script is hung up. Currently transfers are taking upwards of 40 minutes. 

### Fix recommendation:

Add additional logging output to indicate that data is being transferred over to the new instance.

`s3 sync [--progress]` <-- `progress` isn't part of the aws cli to date.

**Comment by ferricoxide** [comment]
Probably _not_ going to do this: the entire `sync`-based process is going to get replaced with something faster.

**Comment by murphyj21** [comment]
As long as it provides some output...limbo sucks.

**Comment by ferricoxide** [comment]
Closed by #19
